apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-public
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cert-manager.io/cluster-issuer: letsencrypt-http01
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - auth.ryuwon.me
      secretName: authentik-public-tls
  rules:
    - host: auth.ryuwon.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-server
                port:
                  number: 80
