apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: ryuwon-platform
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.20.2
    helm:
      releaseName: cert-manager
      values: |
        crds:
          enabled: true
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jqPathExpressions:
        - '.metadata.annotations."kubectl.kubernetes.io/last-applied-configuration"'
        - '.metadata.labels."app.kubernetes.io/managed-by"'
        - '.metadata.labels."helm.sh/chart"'
        - '.spec.template.metadata.labels."app.kubernetes.io/managed-by"'
        - '.spec.template.metadata.labels."helm.sh/chart"'
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: cert-manager-webhook
      jqPathExpressions:
        - ".webhooks[]?.clientConfig.caBundle"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
