apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: ryuwon-platform
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ryuwon-dev/lab.git
    targetRevision: main
    path: platform/workloads/n8n
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: n8n-data
      namespace: n8n
      jsonPointers:
        - /spec/volumeName
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
