apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: ryuwon-platform
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.18.5
    helm:
      releaseName: sealed-secrets
      values: |
        fullnameOverride: sealed-secrets-controller
        namespace: sealed-secrets
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jqPathExpressions:
        - '.metadata.annotations."kubectl.kubernetes.io/last-applied-configuration"'
        - '.metadata.labels."app.kubernetes.io/managed-by"'
        - '.metadata.labels."helm.sh/chart"'
        - '.spec.template.metadata.labels."app.kubernetes.io/managed-by"'
        - '.spec.template.metadata.labels."helm.sh/chart"'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
