apiVersion: v1
kind: ServiceAccount
metadata:
  name: portal-runtime
  namespace: portal
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: portal
    app.kubernetes.io/instance: portal
