apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argo.ryuwon.me
  admin.enabled: "false"
  users.anonymous.enabled: "false"
  oidc.config: |-
    name: Authentik
    issuer: https://auth.ryuwon.me/application/o/argocd/
    clientID: 7TnYIMVoIwMJIP8yrAEZNbYkMl1oGEPZAqo9Z96j
    clientSecret: $argocd-oidc-authentik:clientSecret
    requestedScopes:
      - openid
      - profile
      - email
      - groups
