apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: ""
  scopes: "[groups, email]"
  policy.csv: |-
    g, ryuwon-admins, role:admin
    g, ryuwon-observers, role:readonly
    g, authentik Read-only, role:readonly
