apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: status
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: status-static
    files:
      - index.html
      - styles.css
      - app.js
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: status
    app.kubernetes.io/instance: status
