apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-runtime
  namespace: status
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: status
    app.kubernetes.io/instance: status
