apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http01
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  acme:
    email: letsencrypt@ryuwon.me
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-http01-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
