apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n-outpost
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  ingressClassName: traefik
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.ryuwon.me`) && PathPrefix(`/outpost.goauthentik.io`)
      kind: Rule
      priority: 100
      services:
        - name: authentik-outpost
          port: 80
  tls:
    secretName: n8n-public-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cert-manager.io/cluster-issuer: letsencrypt-http01
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: n8n-authentik-forward-auth@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - n8n.ryuwon.me
      secretName: n8n-public-tls
  rules:
    - host: n8n.ryuwon.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
